// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2ijeC1JssDGSdbgKHwyUsE8VLL9vux4',
    appId: '1:566837640977:web:3b685e64963db7295b56b0',
    messagingSenderId: '566837640977',
    projectId: 'shrubhub-ec955',
    authDomain: 'shrubhub-ec955.firebaseapp.com',
    storageBucket: 'shrubhub-ec955.appspot.com',
    measurementId: 'G-S8NXP0BWGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7EScfJCbML4YDZjhuywHnigZU9rPzyGI',
    appId: '1:566837640977:android:b20343cfeb9b96af5b56b0',
    messagingSenderId: '566837640977',
    projectId: 'shrubhub-ec955',
    storageBucket: 'shrubhub-ec955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1kzAa9RQpC_TY4xR4HLFbaDVTqCnHxbA',
    appId: '1:566837640977:ios:e3909c3475b8dbb55b56b0',
    messagingSenderId: '566837640977',
    projectId: 'shrubhub-ec955',
    storageBucket: 'shrubhub-ec955.appspot.com',
    iosClientId: '566837640977-aof2tetirpcumnvdvdpbtmhse25itvlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shrubHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1kzAa9RQpC_TY4xR4HLFbaDVTqCnHxbA',
    appId: '1:566837640977:ios:1cd93544b348cb265b56b0',
    messagingSenderId: '566837640977',
    projectId: 'shrubhub-ec955',
    storageBucket: 'shrubhub-ec955.appspot.com',
    iosClientId: '566837640977-imptl3cb40jim8ars91ijbjfmrt8nv1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.shrubHub.RunnerTests',
  );
}
